title: Marvel Universe
email: hi@marvel.universe
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Marvel Universe.
baseurl: "/marvel-jekyll-template/" # the subpath of your site, e.g. /blog
url: salimbenfarhat.github.io # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-feed

collections:
  heroes:
    output: true
    permalink: /heroe/:name
  villains:
    output: true
    permalink: /villain/:name

defaults:

